apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= name %>
  namespace: <%= project.namespace %>
  labels:
    caninemanaged: 'true'
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    <% if ingress_class_name == "nginx" %>
    nginx.ingress.kubernetes.io/proxy-pass-headers: "*"
    <% end %>
spec:
  ingressClassName: "<%= ingress_class_name %>"
  tls:
  - hosts:
    <% service.domains.each do |domain| %>
    - <%= domain.domain_name.to_json %>
    <% end %>
    secretName: <%= certificate_name %>
  rules:
  <% service.domains.each do |domain| %>
  - host: <%= domain.domain_name.to_json %>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            <% if service.protected? %>
            name: <%= service.name %>-auth-proxy
            <% else %>
            name: <%= service.name %>-service
            <% end %>
            port:
              number: 80
  <% end %>