apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= endpoint.metadata.name %>
  namespace: <%= add_on.name %>
  labels:
    caninemanaged: 'true'
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: "<%= ingress_class_name %>"
  tls:
  - hosts:
    <% domains.each do |domain| %>
    - <%= domain.to_json %>
    <% end %>
    secretName: <%= endpoint.metadata.name %>-tls
  rules:
  <% domains.each do |domain| %>
  - host: <%= domain.to_json %>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            <% if add_on.protected? %>
            name: <%= endpoint.metadata.name %>-auth-proxy
            port:
              number: 80
            <% else %>
            name: <%= endpoint.metadata.name %>
            port:
              number: <%= port %>
            <% end %>
  <% end %>